version: '3.7'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    volumes:
    - .:/usr/src/app
    command:
    - bash
    - -c
    - |
      if [ ! -f "${DB_DATABASE}" ]; then
        touch ${DB_DATABASE}
      fi
      composer install
      php artisan key:generate
      chmod -R 777 *
      php artisan migrate
      exec apache2-foreground
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/templates
    ports:
      - ${DOCKER_PORT}:80
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=mysql_service
