version: '3.7'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    volumes:
    - .:/usr/src/app
    command:
    - bash
    - -c
    - |
      if [ ! -f "${DB_DATABASE}" ]; then
        touch ${DB_DATABASE}
      fi
      composer install
      php artisan key:generate
      chmod -R 777 *
      php artisan migrate
      exec apache2-foreground
  mysql:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT:-3306}:3306
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/templates
    ports:
      - ${DOCKER_PORT}:80
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=mysql_service
