version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - ${DOCKER_PORT}:80
    volumes:
      - database:${DB_DATABASE_DIRECTORY}
      - storage:/usr/src/app/storage
    command:
      - bash
      - -c
      - |
        if [ ! -f "${DB_DATABASE}" ]; then
          touch ${DB_DATABASE}
        fi
        chmod -R 777 *
        php artisan migrate
        exec apache2-foreground
        php artisan schedule:work
volumes:
  database:
  storage:
